import sanitizeHtml from 'sanitize-html'
import {escape,money,renderProductComment} from './views.mjs'
const clean=value=>sanitizeHtml(value||'',{allowedTags:sanitizeHtml.defaults.allowedTags.concat(['img']),allowedAttributes:{...sanitizeHtml.defaults.allowedAttributes,img:['src','alt','width','height']}})
const json=value=>JSON.stringify(value).replace(/</g,'\\u003c')
export function renderProduct(p){
 const legacy=p.metadata?.legacy||{},variants=p.variants||[]
 const archive=p.metadata?.description_migration
 // Keep existing storefront formatting until an editor changes the readable text.
 const description=archive&&p.description===archive.text?archive.html:p.description
 let policies=p.global_policies||{},shortDescription=legacy.short_description||''
 if((legacy.tag_slugs||[]).includes('ready-to-ship-collection')){
  const copy=policies.ready_to_ship||{},pendant=(legacy.category_slugs||[]).some(c=>/pendant/.test(c))
  policies={...policies,...Object.fromEntries(['process_details','process_details_for_full_custom','process_details_for_flash_sale','process_details_for_semi_deposit'].map(k=>[k,copy.process||policies[k]])),refund_returns:copy.refund||policies.refund_returns,shipping_policy:copy.shipping||policies.shipping_policy,faqs:{items:(copy.faqs||[]).filter((_,i)=>pendant||i>0)}}
  shortDescription=shortDescription.replace(/Pay in Full Ships within 7(?:–|—|-|&ndash;)10 business days\.?\s*(?:Final photos &(?:amp;)? videos will be provided for approval before shipping\.?)?/gi,'Pay in Full Ships within 4–6 business days.')
 }
 const media=[...(p.images?.[0]?.url?[{type:'image',url:p.images[0].url}]:[]),...(legacy.gallery_images||[]),...(legacy.video?[{type:'video',url:legacy.video}]:[])]
 const unique=media.filter((m,i)=>m.url&&media.findIndex(x=>x.url===m.url)===i)
 const full=variants.filter(v=>!/deposit/i.test(v.title||'')),priced=(full.length?full:variants).filter(v=>v.calculated_price)
 const lowest=priced.length?Math.min(...priced.map(v=>Number(v.calculated_price.calculated_amount))):null
 const regular=priced.length?Math.max(...priced.map(v=>Number(v.metadata?.catalog_pricing?.regular_price??v.calculated_price.original_amount))):null
 const sale=legacy.seckill,active=sale?.enabled&&(sale.total==null||sale.total>0)&&(!sale.end_ts||sale.end_ts*1000>Date.now())
 const initial=lowest==null?'Contact us for a quote':`<small>From </small><span>${money(lowest)}</span>${active&&regular>lowest?` <del>${money(regular)}</del>`:''}`
 const labels=legacy.option_labels||{},label=value=>labels[value]||String(value).replace(/-/g,' ').replace(/\b\w/g,c=>c.toUpperCase())
 const options=[...(p.options||[])].sort((a,b)=>['Material','Payment Type','Color'].indexOf(a.title)-['Material','Payment Type','Color'].indexOf(b.title))
 const optionValues=o=>(o.values||[]).filter(v=>!legacy.semi_full_payment_only||!/payment/i.test(o.title)||!/deposit/i.test(v.value))
 const defaultOptions=options.every(o=>optionValues(o).length===1)
 const process=legacy.is_ready_to_ship?policies.process_details:legacy.is_semi?(legacy.semi_deposit?policies.process_details_for_semi_deposit:policies.process_details):(active?policies.process_details_for_flash_sale:policies.process_details_for_full_custom)
 const faq=policies.faqs||{}
 const tabs=[['specifications','Specifications',clean(legacy.specifications||description).replace(/\r?\n/g,'<br>')],['process','Process Details',clean(process)||'<a href="/custom-jewelry-process/">Custom jewelry process</a>'],['faqs','Faqs',`<h2>${escape(faq.title||'Frequently asked questions')}</h2>${clean(faq.description)}${(faq.items||[]).map(x=>`<details><summary>${escape(x.question)}</summary>${clean(x.answer)}</details>`).join('')}`],['returns','Refund&Returns',clean(policies.refund_returns)],['shipping','Shipping Policy',clean(policies.shipping_policy)]]
 return `<section class="d4u-product" data-product-id="${escape(p.id)}"><div class="d4u-gallery"><div class="d4u-gallery-stage"><button class="d4u-image" aria-label="Enlarge product image"><img id="gallery-main" src="${escape(unique[0]?.url||p.thumbnail)}" alt="${escape(p.title)}"></button><video id="gallery-video" controls playsinline hidden></video><button class="gallery-arrow gallery-prev" aria-label="Previous image">‹</button><button class="gallery-arrow gallery-next" aria-label="Next image">›</button></div><div class="d4u-gallery-thumbs">${unique.map((m,i)=>`<button type="button" data-media-index="${i}" data-media-type="${escape(m.type)}" data-media-url="${escape(m.url)}" aria-label="View ${m.type} ${i+1}" aria-pressed="${i===0}">${m.type==='video'?`<video muted playsinline preload="metadata" src="${escape(m.url)}"></video><span>▶</span>`:`<img src="${escape(m.url)}" alt="${escape(p.title)}" loading="lazy">`}</button>`).join('')}</div></div>
 <div class="d4u-product-info"><h1>${escape(p.title)}</h1><div class="d4u-product-tags">${(legacy.tags||[]).map(t=>`<a href="/list/?tags=${encodeURIComponent(t.slug)}" class="d4u-tag">${escape(t.name)}</a>`).join('')}</div><div class="d4u-offer"><p class="d4u-price ${active?'on-sale':''}" id="variant-price">${initial}</p>${active?`<div class="d4u-sale-stock">${sale.total!=null?`<progress max="${Number(sale.total)+Number(sale.sold||0)||1}" value="${Number(sale.total)}"></progress>`:''}<div><span>${sale.total!=null?'Only '+Number(sale.total)+' left':''}</span><span>${Number(sale.sold||0)} sold</span></div>${sale.end_ts?`<p data-sale-countdown="${Number(sale.end_ts)}">Limited-time offer</p>`:''}</div>`:''}</div>
 <div class="d4u-short-description">${clean(shortDescription).replace(/\r?\n/g,'<br>')}</div>
 <form id="product-form">${options.filter(o=>!(o.title==='Option'&&o.values?.length===1&&o.values[0].value==='Default')).map(o=>{const values=optionValues(o);return `<label>${escape(o.title)}<select name="${escape(o.id)}" required>${!defaultOptions?'<option value="">Choose an option</option>':''}${values.map(v=>`<option value="${escape(v.value)}">${escape(label(v.value))}</option>`).join('')}</select></label>`}).join('')}${options.filter(o=>o.title==='Option'&&o.values?.length===1&&o.values[0].value==='Default').map(o=>`<input type="hidden" name="${escape(o.id)}" value="Default">`).join('')}
 <input type="hidden" name="quantity" value="1"><button type="submit" id="add-to-bag">Add to cart</button><button type="button" id="buy-paypal" class="d4u-paypal">Pay with <strong>PayPal</strong></button><p id="product-message" role="status"></p></form>
 <div class="d4u-assurances"><img src="https://img.365d4u.com/c365/2025/11/20251105-103647.png" alt="3–5 Days Express"><img src="https://img.365d4u.com/c365/${legacy.is_ready_to_ship?'2026/09/365day.png':'2025/11/20251105-103703.png'}" alt="${legacy.is_ready_to_ship?'365-Day Limited Warranty':'1.5-Year Warranty'}"></div>
 <div class="d4u-product-links"><button class="d4u-link" data-wishlist="${escape(p.id)}">♡ Save to wishlist</button><a href="https://www.instagram.com/m/365d4u_ada" target="_blank" rel="noopener">Chat with us</a></div></div></section>
 <section class="d4u-product-details"><div class="d4u-tabs" role="tablist" aria-label="Product information">${[...tabs,['reviews','Review']].map(([id,title],i)=>`<button type="button" role="tab" id="tab-${id}" data-product-tab="${id}" aria-controls="panel-${id}" aria-selected="${i===0}" tabindex="${i===0?0:-1}">${title}</button>`).join('')}</div>${tabs.map(([id,title,content],i)=>`<section role="tabpanel" id="panel-${id}" aria-labelledby="tab-${id}" ${i?'hidden':''}>${content||`<a href="/${id==='shipping'?'shipping-policy2':'refund_returns'}/">${title}</a>`}</section>`).join('')}
 <section role="tabpanel" id="panel-reviews" aria-labelledby="tab-reviews" hidden><div id="product-reviews"><h2>Product comments (${p.product_reviews?.total||0})</h2>${(p.product_reviews?.reviews||[]).map(r=>renderProductComment(r)).join('')||'<p>No product comments yet.</p>'}<div>${p.product_reviews?.current_page>1?`<a href="?review_page=${p.product_reviews.current_page-1}#product-reviews">Previous</a>`:''} ${p.product_reviews?.current_page<p.product_reviews?.max_pages?`<a href="?review_page=${p.product_reviews.current_page+1}#product-reviews">Next</a>`:''}</div><details><summary>Write a comment</summary><form id="product-review-form"><input type="hidden" name="product_id" value="${escape(p.id)}"><input type="hidden" name="parent_id" value=""><p id="product-reply-to"></p><label>Name<input name="name" required maxlength="100"></label><label>Email<input type="email" name="email" required></label><label>Review<textarea name="content" required minlength="3" maxlength="5000"></textarea></label><label>Photos / videos<input type="file" name="media" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4" multiple></label><button>Submit comment</button><p role="status" id="product-review-message"></p></form></details></div></section></section>
 <script defer src="/assets/product-reviews.js"></script><script type="application/json" id="product-data">${json({...p,initial_price_html:initial})}</script><dialog id="image-lightbox"><button aria-label="Close">×</button><img alt="Product detail"></dialog>`
}
