import sanitizeHtml from 'sanitize-html'
export const escape = s => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
export const money = (n,currency='USD') => new Intl.NumberFormat('en-US',{style:'currency',currency}).format(Number(n||0))
export const variantLabel = value => String(value||'').split(' / ').map(v=>({'brassmoissanites':'Brass & Moissanites','s925-silver-moissanites':'925 Silver & Moissanites','deposit':'Deposit','full-payment':'Full Payment','14k-gold-color':'14K Gold Color','rose-gold-color':'Rose Gold Color','white-gold-color':'White Gold Color'})[v]||v.replace(/-/g,' ')).join(' / ')
const json = obj => JSON.stringify(obj).replace(/</g,'\\u003c')
export {renderProduct} from './product-view.mjs'
export function renderCart(cart) {
  if(!cart?.items?.length)return '<section class="d4u-panel"><h1>Your bag is empty</h1><a class="d4u-button" href="/list/?all=1">Continue shopping</a></section>'
  return `<section class="d4u-panel"><h1>Your shopping bag</h1><div class="d4u-cart-layout"><div>${cart.items.map(item=>`<article class="d4u-cart-item"><img src="${escape(item.thumbnail)}" alt="${escape(item.title)}"><div><a href="/product/${escape(item.product_handle)}/">${escape(item.title)}</a><p>${escape(variantLabel(item.variant_title))}</p><p>${money(item.unit_price,cart.currency_code)}</p><label>Quantity<input type="number" min="0" max="100" value="${item.quantity}" data-cart-quantity="${escape(item.id)}"></label><button class="d4u-link" data-remove-item="${escape(item.id)}">Remove</button></div></article>`).join('')}</div><aside class="d4u-summary"><h2>Order summary</h2><p>Subtotal <strong>${money(cart.item_subtotal,cart.currency_code)}</strong></p><p>Shipping calculated at checkout.</p><a class="d4u-button" href="/checkout/">Proceed to checkout</a><a href="/list/?all=1">Continue shopping</a></aside></div><p role="status" id="cart-message"></p></section>`
}
export function renderCheckout(cart) {
  if(!cart?.items?.length)return renderCart(cart)
  const fields=[['email','Email','email'],['first_name','First name','text'],['last_name','Last name','text'],['address_1','Street address','text'],['address_2','Apartment, suite (optional)','text'],['city','City','text'],['province','State / province','text'],['postal_code','Postal / ZIP code','text'],['phone','Phone','tel']]
  return `<section class="d4u-panel"><h1>Checkout</h1><div class="d4u-cart-layout"><div><form id="checkout-address"><h2>Contact &amp; shipping</h2><div class="d4u-fields">${fields.map(([name,label,type])=>`<label>${label}<input name="${name}" type="${type}" ${['address_2','province'].includes(name)?'':'required'} value="${escape(name==='email'?cart.email:cart.shipping_address?.[name])}" autocomplete="${name==='email'?'email':name==='phone'?'tel':'on'}"></label>`).join('')}<label>Country<select name="country_code" required>${(cart.region?.countries||[{iso_2:'us',display_name:'United States'}]).map(c=>`<option value="${c.iso_2}" ${(cart.shipping_address?.country_code||'us')===c.iso_2?'selected':''}>${escape(c.display_name)}</option>`).join('')}</select></label></div><button type="submit">Continue to delivery</button></form>
  <section id="checkout-delivery" hidden><h2>Delivery</h2><div id="shipping-options"></div></section><section id="checkout-payment"><h2>Payment</h2><p id="payment-instructions">Enter your shipping address to confirm delivery and activate payment.</p><div id="payment-options" aria-live="polite"></div><div id="paypal-buttons"></div><div id="oceanpayment-element"></div><div id="oceanpayment-applepayelement"></div></section><p id="checkout-message" role="status"></p></div>
  <aside class="d4u-summary"><h2>Your order</h2><div class="d4u-checkout-items">${cart.items.map(i=>`<article class="d4u-checkout-item"><img src="${escape(i.thumbnail)}" alt="${escape(i.product_title||i.title)}"><div><a href="/product/${escape(i.product_handle)}/">${escape(i.product_title||i.title)}</a><p>${escape(variantLabel(i.variant_title))}</p><p>${money(i.unit_price,cart.currency_code)} × ${Number(i.quantity)}</p><strong data-line-total="${escape(i.id)}">${money(i.subtotal??i.unit_price*i.quantity,cart.currency_code)}</strong></div></article>`).join('')}</div><dl class="d4u-totals"><div><dt>Subtotal</dt><dd id="checkout-subtotal">${money(cart.item_subtotal,cart.currency_code)}</dd></div><div><dt>Delivery</dt><dd id="checkout-shipping">Calculated after address</dd></div><div><dt>Discount</dt><dd id="checkout-discount">−${money(cart.discount_total,cart.currency_code)}</dd></div><div><dt>Tax</dt><dd id="checkout-tax">${money(cart.tax_total,cart.currency_code)}</dd></div><div class="d4u-total"><dt>Total</dt><dd id="checkout-total">${money(cart.total,cart.currency_code)}</dd></div></dl><p>By placing your order you agree to our <a href="/terms-conditions/">terms and conditions</a>.</p><a href="/cart/">Edit shopping bag</a></aside></div></section>`
}
export function renderAccount(route) {
  return `<section class="d4u-panel"><h1>My account</h1><nav class="d4u-account-nav"><a href="/my-account/">Account</a><a href="/my-account/orders/">Orders</a><a href="/collect/">Wishlist</a><a href="/contact/">Support</a></nav><div id="account-content"><div class="d4u-account-grid"><form id="login-form" method="post" action="/api/account/login" novalidate><h2>Sign in</h2><label>Email<input type="email" name="email" autocomplete="email" required></label><label>Password<input type="password" name="password" autocomplete="current-password" required></label><button>Sign in</button></form><form id="register-form" method="post" action="/api/account/register" novalidate><h2>Create an account</h2><label>First name<input name="first_name" required></label><label>Last name<input name="last_name" required></label><label>Email<input type="email" name="email" autocomplete="email" required></label><label>Password<input type="password" name="password" minlength="10" autocomplete="new-password" required></label><button>Create account</button></form></div></div><p id="account-message" role="status"></p></section>`
}
export function renderWishlist() {return '<section class="d4u-panel"><h1>My wishlist</h1><div id="wishlist-products" class="d4u-wishlist-grid"></div></section>'}
export function renderReviews(data){
  const list=data.reviews.map(r=>`<div class="review-item"><div class="review-header"><div class="reviewer-avatar">${escape((r.reviewer_name||'C')[0])}</div><div class="reviewer-info"><div class="reviewer-name">${escape(r.reviewer_name)}</div><div class="review-date">${escape(String(r.review_date||'').slice(0,10))}</div></div><div class="review-rating">${'★'.repeat(Math.max(0,Math.min(5,Number(r.rating))))}</div></div><div class="review-content">${r.title?`<h3>${escape(r.title)}</h3>`:''}<div class="review-text">${escape(r.content)}</div></div><div class="review-media"><div class="media-grid">${(r.media||[]).map(m=>`<div class="media-item">${m.type==='video'?`<video controls playsinline preload="metadata" src="${escape(m.url)}"></video>`:`<a href="${escape(m.url)}" target="_blank" rel="noopener"><img loading="lazy" src="${escape(m.url)}" alt="Customer review image"></a>`}</div>`).join('')}</div></div></div>`).join('')
  const pages=new Set([1,data.current_page-1,data.current_page,data.current_page+1,data.max_pages])
  const pagination=[...pages].filter(p=>p>0&&p<=data.max_pages).sort((a,b)=>a-b).map(p=>`<a class="pagination-btn pagination-number ${p===data.current_page?'active':''}" href="/customer-says/?rvpage=${p}" ${p===data.current_page?'aria-current="page"':''}>${p}</a>`).join('')
  return {list,pagination,info:`Page ${data.current_page} of ${data.max_pages} · ${data.total} reviews`}
}

export function renderProductComment(r,depth=0){return `<article style="border-bottom:1px solid #ddd;padding:18px 0;margin-left:${depth&&depth<4?12:0}px"><strong>${escape(r.reviewer_name)}</strong><small> · ${escape(String(r.review_date).slice(0,10))}</small><p style="white-space:pre-wrap">${escape(r.content)}</p>${(r.media||[]).map(m=>m.type==='video'?`<video controls playsinline style="max-width:180px" src="${escape(m.url)}"></video>`:`<img style="max-width:120px" loading="lazy" src="${escape(m.url)}" alt="Product comment">`).join('')}<p><button type="button" data-comment-reply="${escape(r.id)}" data-comment-name="${escape(r.reviewer_name)}">Reply</button></p>${depth<10?(r.children||[]).map(c=>renderProductComment(c,depth+1)).join(''):''}</article>`}
